version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app:celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app:celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"